### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by markhowellsmead** [filamentgroup/imaging-heap#3]
```
X:~ mark$ imagingheap https://filamentgroup.com/
/usr/local/lib/node_modules/imaging-heap/src/cmd.js:41
(async function() {
       ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
```

**Comment by zachleat** [comment]
I’m guessing that you’re running an old version of Node @markhowellsmead? We should have better error messaging for this but it requires Node 8+. `node -v` will tell ya.

**Comment by markhowellsmead** [comment]
Perfect, thanks @zachleat . 👍
